#!/bin/sh
# Since Sublime is fucking insane and can't handle symlinks for the User
# directory, we'll need to manually copy stuff over.

rm -rf $ZSH/sublime2/User
cp -R $HOME/.config/sublime-text-2/Packages/User $ZSH/sublime2/User
