#!/bin/sh
# Setup a machine for Sublime Text 2
echo "configuring sublime-text-2..."
set -x

# symlink settings in
sublime_dir=$HOME/.config/sublime-text-2/Packages
mv "$sublime_dir/User" "$sublime_dir/User.backup"
ln -s "$ZSH/sublime2/User" "$sublime_dir"

# Grab the Soda theme
cd "$sublime_dir"
git clone https://github.com/buymeasoda/soda-theme/ "Theme - Soda"

# Grab the Sublime Package Control
rm -rf "$HOME/.config/sublime-text-2/Installed Packages/Package Control.sublime-package"
wget -P $HOME/.config/sublime-text-2/Installed\ Packages/ http://sublime.wbond.net/Package%20Control.sublime-package

# cp more Packages
packs=$ZSH/sublime2/Packages

for f in $(ls $packs/); do
  rm -rf $sublime_dir/$f
  ln -s $packs/$f $sublime_dir/$f
done
